/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-110472-g4006c71d19-20230504"
#endif /* AVUTIL_FFVERSION_H */
